language: 
  - java
jdk:
  - oraclejdk8
before_install: 
  - echo "export MAVEN_OPTS='-Xmx512m -XX:MaxPermSize=256m'" > ~/.mavenrc
install: 
  - travis_wait mvn -B install -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.javadoc.skip=true -DskipTests=true && travis_wait mvn test
