sudo:
  - required
language: 
  - java
jdk:
  - oraclejdk8
install: 
  - travis_wait mvn -B install -DXmx1G -DXX:MaxPermSize=512m -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -DskipTests -Dmaven.javadoc.skip=true && travis_wait mvn test
